/** \file      sender.c
  *  
  * \brief     Component implementation
  * 
  * [$crn:2005:doxygen 
  * \copyright Copyright 2005 - 2007 LiveDevices Ltd.
  *            Copyright 2007 - 2008 ETAS Engineering Tools Application and Services Ltd.
  *            Copyright 2008 - 2018 ETAS GmbH.
  * $]
  * www.etasgroup.com
  *
  * $Rev: 19024 $ $Date: 2010-07-01 12:57:08 +0100 (Thu, 01 Jul 2010) $
  */

#include "Rte_SenderComponent.h" /* Generated by RTEGen */

/* ---------------------------------------------------------------------- */
/* Runnable: SenderComponent.OSTriggered
 *  
 * Event: /autosar/SenderInternal/PollPeriod 
 * Event type: TIMING-EVENT (1.0s)
 * Mode disabling dependencies: No
 */

FUNC(void, RTE_APPL_CODE)
Sender_OSTriggered(Rte_Instance self) 
{
  ExecutionCountType* s = Rte_Pim_ExecutionCount(self);
  
  (*s)++;

  Rte_Write_OutputPort_CaseStudyData(self, *s);
  
}
