= AsciiDoc Support in EHANDBOOK 

This document provides brief information on the AsciiDoc functionality in general and the supported features and special meanings within EHANDBOOK.

The AsciiDoc converter is part of the Directory-based EHANDBOOK Container-Build Tool-Chain and generates textual and graphical content for EHANDBOOK containers from AsciiDoc files. 

https://asciidoc.org/[AsciiDoc] is a lightweight markup language for authoring documentation in plain text. Any kind of text editor can be used to create the files.
There are many ASCII characters that have special meaning in the context of AsciiDoc.

*EHANDBOOK:* File extension must be *.adoc or *.asciidoc for EHANDBOOK.
EHANDBOOK supports only a subset of the AsciiDoc functionality. 
Other features than described below may also work, but are not guaranteed by ETAS.

Now let's have a look into some of these magic Ascii characters and start with a header:

== Document Header and Section Titles

A document header represents the title of the document. The document header can be followed by text, images, lists, tables, or section titles.

Document title syntax: using '=' character(s) at the very beginning of a new line:

 = Document Header Text (Level 0)

 == Level 1 Section Title

 === Level 2 Section Title

 ==== Level 3 Section Title

 == Another Level 1 Section Title

will look in EHANDBOOK as follows:

== Level 1 Section Title

=== Level 2 Section Title

==== Level 3 Section Title

== Another Level 1 Section Title

More information can be found in https://asciidoctor.org/docs/asciidoc-syntax-quick-reference/#section-titles

*EHANDBOOK:* For EHANDBOOK, the document header is expected as the very first line in the document. 

If the document header is not present, then the name of the folder in which the AsciiDoc file resides will be considered as the document title.
Each subsection title appears as a subchapter in the TOC in EHANDBOOK-NAVIGATOR.

== Formatted Text 

Text style syntax: framing of text by special characters

Formatted text such as \*bold*, \_italic_, \^super^script phrase, \~sub~script phrase are supported. Nested formatting such as \*\_bold-italic_*  is also possible.

Will look in EHANDBOOK as:

Formatted text such as *bold*, _italic_, ^super^script phrase, ~sub~script phrase are supported. Nested formatting such as *_bold-italic_*  is also possible.

More information can be found in https://asciidoctor.org/docs/asciidoc-syntax-quick-reference/#formatted-text

== Lists 

Ordered List Syntax: using the '.' character at the beginning of a new line 
 
 '.' Ordered list can have a list title, followed by list elements in separate lines
 '.' In an ordered list, list elements start with a dot '.' 

Will look in EHANDBOOK as:

. Ordered list can have a list title followed by list elements in separate lines
. In an ordered list, list elements start with a dot '.' 

Unordered List Syntax: using the '-' or '*' character at the beginning of a new line 
 
 '-' Unordered list can have a list title followed by list elements in separate lines
 '-' Unordered list element starts with hyphen '-'
 '*' Alternatively, an unordered list element can start with an asterisk 

Will look in EHANDBOOK as:

- Unordered list can have a list title followed by list elements in separate lines.
- Unordered list element starts with hyphen '-'
* Alternatively, an unordered list element can start with an asterisk

A blank line is required before and after a list to separate it from other blocks.

More information can be found in  https://asciidoctor.org/docs/asciidoc-syntax-quick-reference/#lists

*EHANDBOOK:* Only basic ordered and unordered lists without nesting are supported in EHANDBOOK.

== Tables

Table with title has the following syntax:

 .Table title 

 |===
 |TableHead1 |TableHead2 |TableHead3 

 |Cell in column 1, row 1
 |Cell in column 2, row 1
 |Cell in column 3, row 1

 |Cell in column 1, row 2
 |Cell in column 2, row 2
 |Cell in column 3, row 2
 |===

Will look in EHANDBOOK as:

.Table title 

|===
|TableHead1 |TableHead2 |TableHead3 

|Cell in column 1, row 1
|Cell in column 2, row 1
|Cell in column 3, row 1

|Cell in column 1, row 2
|Cell in column 2, row 2
|Cell in column 3, row 2
|===

More information can be found in  https://asciidoctor.org/docs/asciidoc-syntax-quick-reference/#tables

*EHANDBOOK:* Only simple tables are supported in EHANDBOOK (equal columns and rows, no nesting).
The sortable headers and the filter line is added by EHANDBOOK automatically.


== Images in EHANDBOOK

Images can be embedded in AsciiDoc documentation. In EHANDBOOK, model screenshots can be linked to interactive models by providing the link to the model path.

=== Embed pre-generated images

Image must be placed in the same folder as the Asciidoc documentation or 
in a subfolder of the Asciidoc documentation. In either case path relative to Asciidoc documentation is expected. 

 Syntax: image::VectorImage.svg[]

image::VectorImage.svg[]

*EHANDBOOK:* Pre-generated images in svg, jpg and png formats are supported.

=== Pre-generated Images linked with Model

Pre-generated image can also be linked to its corresponding hierarchy of the interactive model in EHANDBOOK-NAVIGATOR. 

 Syntax: image::image_name.svg[link=ehbmodelref:model_path]

image::VectorImage.svg[link=ehbmodelref:model_ICC]

=== EHANDBOOK generated Images linked with Model

Model hierarchy screenshot made by EHANDBOOK and linked to the interactive model in EHANDBOOK-NAVIGATOR.

 Syntax: ehbmodelref::model_path[image_title]

ehbmodelref::model_ICC/ICC_mdl[image_title]

=== EHANDBOOK generated Function Overview Image

A function overview image is generated by EHANDBOOK from the model(s) inputs and outputs

 Syntax for one Function only: ehbfunctionoverview::function_name[title]

ehbfunctionoverview::Documentation[Title Name]

 Syntax for multiple functions: ehbfunctionoverview::function1_name[title],function2_name[title]

 Syntax for all the functions of the container: ehbfunctionoverview-all::[title]

== Include Files 

=== Inclusion of other AsciiDoc or source files

Contents from another AsciiDoc file or other file formats can be inlined within this AsciiDoc document. 

*EHANDBOOK:* File to be inlined must be placed in the same folder as the Asciidoc documentation or in a subfolder of the Asciidoc documentation. 
In either case path relative to Asciidoc documentation is expected.
To inline the content from another AsciiDoc file into the main AsciiDoc file, the name of the file to be inlined should start with an underscore '_'.

If multiple AsciiDoc files are used without '_', the content of each file is appended in EHANDBOOK in alphabetical order of the file names.

 Syntax for inlining files: include::_fileName.extension[]
 
include::./../../include/_anotherFile.asciidoc[]

=== Inclusion of Formatted Source Code, e.g. C-Code

 Syntax for inlining source files: 
 [source,c] 
 ----
 include::filename.extension[]
 ----

Will look in EHANDBOOK as:

[source,c]

----
include::./../../include/add.c[]
----

*EHANDBOOK:* Syntax highlighting is not supported in EHANDBOOK.

== Links

=== AutoLink

AsciiDoc recognizes the following common URL schemes without the help of any markup:

. http / https

. file

. mailto

. ftp

. irc


So the below https URL automatically turn it into a hyperlink:

The EHANDBOOK homepage is https://www.etas.com/ehandbook

A link to an external file works like this:

file://C:/ETAS/EHANDBOOK-NAVIGATOR9.1/demo/EHANDBOOK_FlexECU_Demo.pdf

By click on the link, the file will be opened with the associated tool outside of EHANDBOOK-NAV.

AsciiDoc also detects and autolinks standard email addresses:

Email us at sales.de@etas.com for any inquiries.

*EHANDBOOK:* Only absolute file paths are supported in EHANDBOOK.

=== Customize Link Text

The appearance of the link can be configured. 
This is done by appending text or parameters, enclosed by a pair of square brackets.

==== Customize URL and File Link Text

Instead of the link itself, an alternative text can be displayed.
Insert that text between the square brackets at the end of the URL.

\https://etas.com/ehandbook [Show Homepage] will be shown as:

https://etas.com/ehandbook[Show Homepage]

Since the text is subject to normal substitutions, you can apply formatting to it.

https://etas.com/ehandbook[*Show Homepage*]

And out of this 

\file://C:/ETAS/EHANDBOOK-NAVIGATOR9.1/demo/EHANDBOOK_FlexECU_Demo.pdf [Show Me]

the following is shown:

file://C:/ETAS/EHANDBOOK-NAVIGATOR9.1/demo/EHANDBOOK_FlexECU_Demo.pdf[Show Me]

==== Customize Mailto Text

For mailto, two parameters are used inside the brackets. The first parameter defines the text that is shown as the link. 
The second parameter defines the text that will appear in the subject field of your mail program.  

mailto:sales.de@etas.com[Contact ETAS,Request for Quotation]

If you want to leave the linked text blank (so it falls back to the email address), 
start the attribute list with a comma so as to leave a blank slot for it.

mailto:sales.de@etas.com[,Request for Quotation]

=== Link Macro

The general link syntax is \link:<target>[<attrlist>]

The link macro is required if the link does not start with a scheme recognized by AsciiDoc.
This is also necessary if the link contains any space characters. In this case, the space must be encoded by %20 or &#32;

\link:file:///c:/ETAS/EHANDBOOK-NAVIGATOR9.1/documentation/EHANDBOOK-NAVIGATOR%20Getting%20Started.pdf [Get Started] 

becomes:

link:file:///c:/ETAS/EHANDBOOK-NAVIGATOR9.1/documentation/EHANDBOOK-NAVIGATOR%20Getting%20Started.pdf[Get Started]


== Formulas

[plantuml,scale1_5]
....
@startmath
scale 1.5
f(t)=(a_0)/2 + sum_(n=1)^ooa_ncos((npit)/L)+sum_(n=1)^oo b_n\ sin((npit)/L)
@endmath
....

[plantuml,scale3_5]
....
@startmath
scale 3.5
f(t)=(a_0)/2 + sum_(n=1)^ooa_ncos((npit)/L)+sum_(n=1)^oo b_n\ sin((npit)/L)
@endmath
....

[plantuml,default]
....
@startmath
f(t)=(a_0)/2 + sum_(n=1)^ooa_ncos((npit)/L)+sum_(n=1)^oo b_n\ sin((npit)/L)
@endmath
....

Image type svg

[plantuml,latex_svg,svg]
....
@startlatex
\sum_{i=0}^{n-1} (a_i + b_i^2)
@endlatex
....

== UML Diagrams

=== Sequence Diagram

[plantuml,sequence1]

....
Alice -> Bob: Authentication Request
Bob --> Alice: Authentication Response

Alice -> Bob: Another authentication Request
Alice <-- Bob: Another authentication Response
....

=== Use Case Diagram

[plantuml,usecase2]
....
@startuml
!pragma graphviz_dot smetana

(First usecase)
(Another usecase) as (UC2)
usecase UC3
usecase (Last\nusecase) as UC4

@enduml
....

=== Class Diagram

[plantuml,Class3]

....
@startuml
!pragma graphviz_dot smetana

abstract class AbstractList
abstract AbstractCollection
interface List
interface Collection

List <|-- AbstractList
Collection <|-- AbstractCollection

Collection <|- List
AbstractCollection <|- AbstractList
AbstractList <|-- ArrayList

class ArrayList {
  Object[] elementData
  size()
}

enum TimeUnit {
  DAYS
  HOURS
  MINUTES
}

annotation SuppressWarnings

@enduml
....

=== Components

[plantuml,Components4]

....
@startuml
!pragma graphviz_dot smetana

[AA] <<static lib>>
[BB] <<shared lib>>
[CC] <<static lib>>

node node1
node node2 <<shared node>>
database Production

skinparam component {
    backgroundColor<<static lib>> DarkKhaki
    backgroundColor<<shared lib>> Green
}

skinparam node {
borderColor Green
backgroundColor Yellow
backgroundColor<<shared node>> Magenta
}
skinparam databaseBackgroundColor Aqua

@enduml
....

=== Object Diagram

[plantuml,Object5]

....
@startuml
!pragma graphviz_dot smetana


object Object01
object Object02
object Object03
object Object04
object Object05
object Object06
object Object07
object Object08

Object01 <|-- Object02
Object03 *-- Object04
Object05 o-- "4" Object06
Object07 .. Object08 : some labels

@enduml
....

=== Deployment Diagram

[plantuml,de6]

....
@startuml
!pragma graphviz_dot smetana

artifact Foo1 {
  folder Foo2
}

folder Foo3 {
  artifact Foo4
}

frame Foo5 {
  database Foo6
}

cloud vpc {
  node ec2 {
    stack stack
  }
}

@enduml
....

=== Timing Diagram

[plantuml,Timing7]

....
@startuml
!pragma graphviz_dot smetana

robust "Web Browser" as WB
concise "Web User" as WU

@0
WU is Idle
WB is Idle

@100
WU -> WB : URL
WU is Waiting
WB is Processing

@300
WB is Waiting

@enduml
....

More information can be found in  https://asciidoctor.org/docs/asciidoctor-diagram/












