#store to properties file
#Fri Sep 16 07:55:09 UTC 2022
header.image=../../css/ETAS-Logo_Blue_sRGB.png
footer.text=© ETAS GmbH reserves all rights even in the event of industrial property rights. We reserve all rights of disposal such as copying and passing on to third parties.
